[package]
name = "michi-pipeline"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
michi-core = { path = "../michi-core", version = "0.1.0" }
michi-resilience = { path = "../michi-resilience", version = "0.1.0" }
tokio = { workspace = true, features = ["time", "rt"] }
thiserror.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros", "rt", "sync"] }
