[package]
name        = "michi-toon"
version     = "0.1.0"
description = "Token-Optimized Object Notation (TOON) format renderer and parser for michi and AXI"
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
compact_str     = { workspace = true, features = ["serde"] }
michi-truncate  = { path = "../michi-truncate", version = "0.1.0" }
serde           = { workspace = true, optional = true }
serde_json      = { workspace = true, optional = true }
schemars        = { workspace = true, optional = true }

[features]
default = []
serde   = ["dep:serde", "dep:serde_json"]
schemars = ["dep:schemars"]
